version: "3"
services:
  strapi:
    container_name: strapi
    build: .
    image: strapi:latest
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: strapiDB
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      JWT_SECRET: strapi
      ADMIN_JWT_SECRET: strapi
      APP_KEYS: strapi
      NODE_ENV: production
    volumes:
      - ./package.json:/opt/package.json
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: mariadb:latest
    environment:
      MYSQL_USER: strapi
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_DATABASE: strapi
    volumes:
      - strapi-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge

